import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Footer from "./components/footer/Footer";
import Header from "./components/header/Header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Менеджер заказов",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   return (
     <html lang="ru" suppressHydrationWarning>
       <body
         className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
       >
         <Providers>
           <div className="flex flex-col min-h-screen">
             {/* Header фиксируется сверху */}
             <Header />

             {/* Основной контент растягивается */}
             <main className="flex-grow px-4 sm:px-6 lg:px-8">
               {children}
             </main>

             {/* Footer фиксируется снизу */}
             <Footer />

             {/* Toaster для уведомлений */}
             {/* <Toaster /> */}
           </div>
         </Providers>
       </body>
     </html>
   );
}
